port-check-conflicts : significant speed-up using bash arrays
Committed from host : Bola

diff --git a/macports/bin/port-check-conflicts b/macports/bin/port-check-conflicts
--- a/macports/bin/port-check-conflicts
+++ b/macports/bin/port-check-conflicts
@@ -1,74 +1,88 @@
-#!/bin/sh
+#!/bin/bash
 
 PORT=""
 OPTS=""
 INVERSE=0
 
 while [ $# != 0 ] ;do
-	case $1 in
-		-v)
-			INVERSE=1
-			;;
-		-*)
-			OPTS="${OPTS} $1"
-			;;
-		*)
-			PORT="${PORT} $1"
-			;;
-	esac
-	shift
+    case $1 in
+        -v)
+            INVERSE=1
+            ;;
+        -*)
+            OPTS="${OPTS} $1"
+            ;;
+        *)
+            PORT="${PORT} $1"
+            ;;
+    esac
+    shift
 done
 
 DNAME="`dirname $0`"
 
 CleanUp() {
-	# nothing to cleanup
-	exit 1
+    # nothing to cleanup
+    exit 1
 }
 
 trap CleanUp 1
 trap CleanUp 2
 trap CleanUp 15
 
+declare -a DUPSarray
+declare -a ORGSarray
+
 if [ "${PORT}" != "" ] ;then
-	for p in $PORT ;do
-		if [ -d "${p}" ] ;then
-			pWD="${p}" ; export pWD
-		else
-			if [ "${_WD_port}" != "${p}" ] ;then
-				pWD="`port work ${p}`" ; export pWD
-				_WD_port="${p}" ; export _WD_port
-			fi
-		fi
-		if [ -e ${pWD}/destroot ] ;then
-			echo "cd ${pWD}/destroot"
-			cd ${pWD}/destroot
-			DUPS=""
-			FILES=`find . -type f`
-			for f in $FILES ;do
-				g="`echo \"${f}\" | sed -e 's|.||'`"
-				if [ -e "${g}" ] ;then
-					if [ ${INVERSE} = 0 ] ;then
-						provider=`port provides "${g}" | sed -e "s|.*is provided by: ||g"`
-						if [ "${provider}" != "${p}" ] ;then
-							echo "${g} already exists"
-							echo "\tprovided by: ${provider}"
-							ls -l ${f} ${g}
-							DUPS="${DUPS}\n${g}"
-						fi
-					fi
-				else
-					if [ ${INVERSE} = 1 ] ;then
-						echo "${g} doesn't exist yet"
-					fi
-				fi
-			done
-			if [ "${DUPS}" != "" ] ;then
-				echo ${DUPS}
-			fi
-			echo
-		fi
-	done
+    for p in $PORT ;do
+        if [ -d "${p}" ] ;then
+            pWD="${p}" ; export pWD
+        else
+            if [ "${_WD_port}" != "${p}" ] ;then
+                pWD="`port work ${p}`" ; export pWD
+                _WD_port="${p}" ; export _WD_port
+            fi
+        fi
+        if [ -e ${pWD}/destroot ] ;then
+            echo "cd ${pWD}/destroot"
+            cd ${pWD}/destroot
+            DUPS=""
+            FILES=`find . -type f`
+            for f in $FILES ;do
+                g="`echo \"${f}\" | sed -e 's|.||'`"
+                if [ -e "${g}" ] ;then
+                    if [ ${INVERSE} = 0 ] ;then
+                        DUPSarray=(${DUPSarray[*]} ${g})
+                        ORGSarray=(${ORGSarray[*]} ${f})
+                    fi
+                else
+                    if [ ${INVERSE} = 1 ] ;then
+                        echo "${g} doesn't exist yet"
+                    fi
+                fi
+            done
+            if [ ${#DUPSarray[*]} != 0 ] ;then
+                # fetch the ports that provide the various dupes found. Do this in one fell swoop
+                # because that's a lot (10x or more) faster than calling `port provides` repeatedly.
+                PROVIDERS=(`port provides ${DUPSarray[*]} | sed -e "s|.*is provided by: ||g"`)
+                for idx in $(seq 0 $((${#DUPSarray[*]} - 1))) ;do
+                    f="${ORGSarray[${idx}]}"
+                    g="${DUPSarray[${idx}]}"
+                    provider="${PROVIDERS[${idx}]}"
+                    if [ "${provider}" != "${p}" ] ;then
+                        echo "${g} already exists"
+                        echo "\tprovided by: ${provider}"
+                        ls -l ${f} ${g}
+                        DUPS="${DUPS}\n${g}"
+                    fi
+                done
+                if [ "${DUPS}" != "" ] ;then
+                    echo ${DUPS}
+                    echo
+                fi
+            fi
+        fi
+    done
 else
-	echo "Usage: `basename $0` [-options] <port1> [port2 [port3 [...]]]"
+    echo "Usage: `basename $0` [-options] <port1> [port2 [port3 [...]]]"
 fi
