port-check-conflicts : use a dedicated port-provides script generated on the fly to avoid commandline length overflow issues.
Committed from host : Portia.local

diff --git a/macports/bin/port-check-conflicts b/macports/bin/port-check-conflicts
--- a/macports/bin/port-check-conflicts
+++ b/macports/bin/port-check-conflicts
@@ -21,9 +21,14 @@ done
 
 DNAME="`dirname $0`"
 
+if [ "${TMPDIR}" = "" ] ;then
+    TMPDIR="/tmp"
+fi
+export PPROV="${TMPDIR}/port-provides-$$.sh"
+
 CleanUp() {
-    # nothing to cleanup
-    exit 1
+    rm -f ${PPROV}
+    exit $1
 }
 
 trap CleanUp 1
@@ -32,6 +37,65 @@ trap CleanUp 15
 
 declare -a DUPSarray
 declare -a ORGSarray
+
+make_pprov_pre () {
+    head -20 `which port` > ${PPROV}
+    chmod 700 ${PPROV}
+    cat >> ${PPROV} <<- EOF
+# cherry-picked shamelessly from `which port`
+package require Tclx
+package require macports
+package require Pextlib 1.0
+
+array set ui_options        {} 
+array set global_options    {}
+array set global_variations {}
+
+proc macports::normalise { filename } {
+    set prefmap [list [file dirname [file normalize "\${macports::prefix}/foo"]] \${macports::prefix}]
+    return [string map \${prefmap} [file normalize \$filename]]
+}
+
+proc action_provides { portlist } {
+    # In this case, portname is going to be used for the filename... since
+    # that is the first argument we expect... perhaps there is a better way
+    # to do this?
+    if { ![llength \$portlist] } {
+        ui_error "Please specify a filename to check which port provides that file."
+        return 1
+    }
+    foreach filename \$portlist {
+        set file [macports::normalise \$filename]
+        if {[file exists \$file] || ![catch {file type \$file}]} {
+            if {![file isdirectory \$file] || [file type \$file] eq "link"} {
+                set port [registry::file_registered \$file] 
+                if { \$port != 0 } { 
+                    puts "\$file is provided by: \$port"
+                } else {
+                    puts "\$file is not provided by a MacPorts port."
+                }
+            } else {
+                puts "\$file is a directory."
+            }
+        } else {
+            puts "\$file does not exist."
+        }
+    }
+    registry::close_file_map
+
+    return 0
+}
+
+# Initialise mport
+# This must be done following parse of global options, as some options are
+# evaluated by mportinit.
+if {[catch {mportinit ui_options global_options global_variations} result]} {
+    puts \$::errorInfo
+    fatal "Failed to initialise MacPorts, \$result"
+}
+
+EOF
+}
 
 if [ "${PORT}" != "" ] ;then
     for p in $PORT ;do
@@ -52,8 +116,8 @@ if [ "${PORT}" != "" ] ;then
                 g="`echo \"${f}\" | sed -e 's|.||'`"
                 if [ -e "${g}" ] ;then
                     if [ ${INVERSE} = 0 ] ;then
-                        DUPSarray=(${DUPSarray[*]} ${g})
-                        ORGSarray=(${ORGSarray[*]} ${f})
+                        DUPSarray+=(${g})
+                        ORGSarray+=(${f})
                     fi
                 else
                     if [ ${INVERSE} = 1 ] ;then
@@ -63,11 +127,20 @@ if [ "${PORT}" != "" ] ;then
             done
             if [ ${#DUPSarray[*]} != 0 ] ;then
                 echo "${#DUPSarray[*]} files already exist, checking if any don't belong to ${p}"
+
+                # construct a temporary tcl script
+                make_pprov_pre
+                echo "set flist {${DUPSarray[*]}}" >> ${PPROV}
+                echo "action_provides \${flist}" >> ${PPROV}
+                echo "mportshutdown" >> ${PPROV}
+
                 # fetch the ports that provide the various dupes found. Do this in one fell swoop
                 # because that's a lot (10x or more) faster than calling `port provides` repeatedly.
                 # Replace the human-readabability text to keep just the port names and placeholder text
                 # without spaces for files not belonging to a port.
-                PROVIDERS=(`port provides ${DUPSarray[*]} | sed -e 's|^.* is not provided by a MacPorts port.$|not_by_MacPorts|g' \
+                # We use the temporary tcl script instead of `port provides` because that allows
+                # argument lines of arbitrary length
+                PROVIDERS=(`${PPROV} | sed -e 's|^.* is not provided by a MacPorts port.$|not_by_MacPorts|g' \
                             -e 's|.*is provided by: ||g'`)
                 for idx in $(seq 0 $((${#DUPSarray[*]} - 1))) ;do
                     f="${ORGSarray[${idx}]}"
@@ -87,6 +160,7 @@ if [ "${PORT}" != "" ] ;then
             fi
         fi
     done
+    CleanUp 0
 else
     echo "Usage: `basename $0` [-options] <port1> [port2 [port3 [...]]]"
 fi
