port-check-conflicts : react quicker to interrupts
Committed from host : Portia.local

diff --git a/macports/bin/port-check-conflicts b/macports/bin/port-check-conflicts
--- a/macports/bin/port-check-conflicts
+++ b/macports/bin/port-check-conflicts
@@ -17,6 +17,15 @@ done
 
 DNAME="`dirname $0`"
 
+CleanUp() {
+	# nothing to cleanup
+	exit 1
+}
+
+trap CleanUp 1
+trap CleanUp 2
+trap CleanUp 15
+
 if [ "${PORT}" != "" ] ;then
 	for p in $PORT ;do
 		if [ "${_WD_port}" != "${p}" ] ;then
