port:kf5-kdevelop-devel : 5.2 WIP. Workaround to avoid the cmake-server-based project import
Committed from host : Portia.local

diff --git a/kf5/kf5-kdevelop/files/cmake2port b/kf5/kf5-kdevelop/files/cmake2port
--- a/kf5/kf5-kdevelop/files/cmake2port
+++ b/kf5/kf5-kdevelop/files/cmake2port
@@ -83,6 +83,13 @@ while [ $# != 0 ] ;do
     if [ ${NOMORECMAKEOPTIONS} = 0 ] ;then
         case $1 in
             -E)
+                if [ "${2}" = "server" -a "`basename $0`" = "cmake2port_noserver" ] ;then
+                    # emulate the error message from an older CMake version
+                    (   echo "CMake Error: cmake version 3.0.1 (faked to avoid server mode)"
+                        echo "Usage: @PREFIX@/bin/cmake -E [command] [arguments ...]"
+                    ) 1>&2
+                    exit 1
+                fi
                 if [ -z "${PWD##*kf5*}" ] ;then
                      # invoked in the build.dir of a kf5 port
                      exec @PREFIX@/bin/cmake-kf5-mp "$@"
